language: node_js
sudo: required
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
env:
  global:
    - secure: >-
        ow6TG0L/Fw+CJWgKXYMMX3MsvckjPzd3ZQQJRB4/UdHc8agUarGnth8heB2zYfBT+KucV34JaPXzEeAijpQuhZLyvMAS63q+ZzQ2C9Js93+f15PU6v1rBzJR/9HN4hhaCJVrfx1uTPeLHeTpQXYpCC9oCTamiWKj53BO4+3YwlQ=
    - secure: >-
        HV0yQ1I1KRUIndDpwB5KPYj/U8qzmXSKkbvlSTukmbmLUABjvtyEHqsn+jEOQODcRJwF7EC6TT0S/qEX5jyjB/lhWjNtmYWeWf63O1VdvtMyAsUrwuZDUTaSJaVvCy3tiqAn4LSu1uHDX5qNVJoyLQROaAPBemhsypXnjot0Lp0=
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run wct
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s ''default''; fi'
dist: trusty
