language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: WxlVbCDRxgNgvyoakDC4HiyUQB/oz3Oy1mvr6vJqGgnV7U1xC89y5FbQsUq27DthHAa5aqumEzZR3PCMzAJ8q/XdK7kbGC1f3KxSGrpVNtJFq7my3UzjWT0OkwXuIOWouio//CGVao3Z0Xp5FQlzQVoZJYo2HIZ8n2SRn7XY9xFBiU/lOPc/EKo5Q7f7Ox4IxNMMPSwT3JuNTeqJXi5c6Uy2GfWA1QkdieJUzSr/kPykiB5ng1rR7MZcNZpmjLVKIq+zcLWV6bWyd6UDK8ySuOgAq56i9ctMburN42anzjdAtPsPBm03F+CdOtDuYS+jHRvpROUkcNAWWt+6GHIj4J/cJ4prHv6nwX9Ta8COCiYpWV7BzgIcpF3j4IuzWKIJUbWhBZCVx3mzqcauHQDL1AvyxQX4gHi5LqUcHGEq0udxMkfnY8xu4p43yApSkOSPzG+9zLo9JU7BvNAy24b+84wf3oKukdltkAlXIEjI/32ddEXjnPDVQH8CMiseUMlht+97itgxOtgRLVP27oBummumy7W81PY1VvT9pjkZUD1xqIfclSjzVdL1POVKLq3lH5oLNy2ZelDp1rOoeLXEGTeXNTPjliGQqttVoJPIw4+GQFwvAhADIeFml6bqeLSMj0WlZDZbh3EDdk4Y9/RI7m7ZZRglIxTvGTLFt4dbkyg=
  - secure: GRJBX6vhTPvM6oewyQXosd1YAQquY/RFqtd4sxjawJeDbcsLZBz/+ohk1qtIPbHsaDCg64ZgRMHwhN+mh6b/DiRGQQz7wTKmAIUFJB3qVWO7WuM6vw9i4PqyoRwFfDIU9RGIceiM+Jk9mJHMkq7xH9VyusqlDRu1zFc7dgm2o7gF01G6feNj0lFR6tqNPJoTTlDiAx+8SXBVwCEckiX6eFWaH3NGKspQ3d2ZVf9qHFVGEEeZ/kO3ZAUedgNdODvl+g4epxHioOTQGA9GyoOJkCC+AFAcHeUUx2prBh6MxJZlA7REGrZ15ZM8SH18qhzYBJuhCyBdpJvtj4ZwO88pdFrdadwSnrGCpd/5ZN80O6m6Sp7D1CaJpDU7a7U8g/ygmqHzX26ILsYKGoaFYKt8oG2WatVxwZyXCXy77fnYBEo9pP/w1Ht5IUSOsPQGKrYQyRd9jKOkdJgK6MJD6URYsW9iwfc3O0ZS+j3ZQuETQvNc5HbxHCWIaFAiPyuu6eZ3P9iOOEkeFQ3LnzxFwwst9yv03u+h4nAJXNvieyvOmVnJePi7NU4AnBmolgQBART6Dif65cgOUtxp23s4hSEz/qci+75RzTYfOM5VnmGSvxLGO2QrUOa4rhOw48I6CuV+oGim/WU64/3JW2Dub8FzFGIUf+GbHCB2rnVmgI3KuVU=
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
